#!/usr/bin/env ruby

# generate local ri docs
#
# Generate RI documentation. This utilizes
# rdoc to produce the appropriate files.

main :ri do
  config, output, input = *ri_configuration

  file output => input do
    ri_target(config)
  end

  build output
end

# Document target.

def ri_target(config)
  output = config['op']
  input  = config.delete('include')

  # Check for 'doc' directory.
  # (Helps to ensure we're in the right place.)
  #dir!(File.dirname(site))

  # Remove old rdocs.
  rm_r(output) if exist?(output) and safe?(output)

  #input = input.collect{ |i| glob(i) }.flatten
  vector = ['--ri', input, config]
  rdoc(vector.to_console)
end

# Collect RDocs configuration.

def ri_configuration
  config = configuration['ri'] || {}

  config = {
    'op'             => 'doc/ri',
    'merge'          => true,
    'exclude'        => [],
    'include'        => ['lib']
  }.merge(config)

  if config['output']
    config['op'] = config.delete('output')
  end

  output = config['op']

  input  = config['include'].collect do |i|
    dir?(i) ? File.join(i,'**','*') : i
  end

  return config, output, input
end
